### ISSUE TITLE
Support More Models

### ISSUE THREAD

**Issue by jstzwj** [ryanhex53/gpt-po#17]
When I used the model gpt-3.5-turbo-1106, I encountered the following error:
error: option '--model <model>' argument 'gpt-3.5-turbo-1106' is invalid. Allowed choices are gpt-4o, gpt-4-turbo, gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301.

I hope this tool can support more model types, such as the o1 model.
Additionally, when using OpenAI-compatible services, I hope the translation tool to work with these models as well, rather than rejecting my model name. For example, the Qwen model and DeepSeek's deepseek-chat. I am using these OpenAI-compatible services because these LLMs are more competitive in terms of pricing.

**Comment by ryanhex53** [comment]
Will update this soon

**Comment by ryanhex53** [comment]
done in version 1.1.2

**Comment by jstzwj** [comment]
Thank you for your lightning fast development!
