### ISSUE TITLE
OpenAI v4 api error.

### ISSUE THREAD

**Issue by acabrol** [ryanhex53/gpt-po#6]
OpenAI pushed a new version (v4).
The project doesn't work anymore: 
`Module '"openai"' has no exported member 'ChatCompletionRequestMessageRoleEnum'`

**Comment by ryanhex53** [comment]
I've just tested on my end, and everything seems to be working correctly. My project is still using `openai@3.2.1`.

To troubleshoot on your side, you can try removing the `node_modules` directory by running `rm -rf node_modules` (be cautious with this command, as it permanently deletes files) and then reinstalling the dependencies with `npm install`.

**Comment by acabrol** [comment]
Ok Thanks i moved to a python version of po translation with gpt as i'm more comfortable with python than node.
